---
title: "Homework_5"
author: "Nikki Johnson"
date: "11/22/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load required packages
library(readr)
library(magrittr)
library(tidyr)
library(dplyr)
library(lubridate)
library(forcats)
library(ggplot2)

#read in data
homicides <- read_csv (file = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
homicides

#filter for baltimore homicides
baltimore <- homicides %>%
  filter(city == "Baltimore")

#pull out month and year
month <- baltimore %>%
  mutate(reported_date = ymd(reported_date)) %>%
  mutate(month = format(reported_date, "%m")) %>%
  mutate(year = format(reported_date, "%y"))

#making month a factor variable
month$month <- as.factor(month$month)

#setting up dates for graph
month$month_year <- format(as.Date(month$reported_date), "%y-%m")

#create season column 
season <- month %>%
  mutate(season = fct_recode(month, 'Winter' = "01",
                             'Winter' = "02",
                             'Winter' = "03",
                             'Winter' = "04",
                             'Summer' = "05",
                             'Summer' = "06",
                             'Summer' = "07",
                             'Summer' = "08",
                             'Summer' = "09",
                             'Summer' = "10",
                             'Winter' = "11",
                             'Winter' = "12"))

#aggregate data and find total by month
season_2 <- season %>%
  select(year, month, season, month_year) %>%
  mutate(month_year = parse_date_time(month_year, "ym")) %>%
  mutate(month_year = ymd(month_year)) %>%
  count(month_year, season, name = 'total') 

#plot data
plot_data <- season_2 %>%
  ggplot(aes(x = month_year, y = total)) +
  geom_col(aes(fill = season)) +
  geom_vline(xintercept = as.numeric(as.Date("2015-04-01")), 
             linetype = 4, size = 2, color = "red") +
  geom_smooth(se = FALSE, span = 0.10) +
  scale_fill_manual(values = c("Winter" = "lightblue", "Summer" = "gray")) +
  scale_x_date(name = "Date", date_labels = "%y") +
  labs(y = "Monthly homicides") +
  ggtitle("Homicides in Baltimore, MD") +
  theme_dark() +
  theme(legend.position = "bottom")
plot_data
```
